### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by simmstein** [traxys/nextpass#1]
Hello, 

Could you write a documentation to install nextpass please?

Thanks

**Comment by traxys** [comment]
There is more information now, those it need more information on running it ?

**Comment by simmstein** [comment]
Build failed but the doc is better :+1:

**Comment by traxys** [comment]
Let me guess, openssl ?

**Comment by simmstein** [comment]
https://gist.github.com/simmstein/9df8761bdb457473fbbd25e1834ebf5b

**Comment by traxys** [comment]
Ok that is a too old version of the compiler, I should mention that too
